---
- name: chmod 777 webapps
      file:
        path: "{{ tomcat_install_path }}/apache-tomcat-{{tomcat_version}}/webapps"
        mode:  777

- name: Setup server.xml
  template:
    src: "{{ tomcat_template_server }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/conf/server.xml"
  notify: restart tomcat

- name: Setup tomcat-users.xml
  template:
    src: "{{ tomcat_template_users }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/conf/tomcat-users.xml"
  notify: restart tomcat

- name: Configure access to Host Manager (from localhost only or from anywhere)
  template:
    src: "{{ tomcat_template_host_manager_context }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/webapps/host-manager/META-INF/context.xml"

- name: starting tomcat
    shell: nohup /usr/local/apache-tomcat-{{tomcat-version}}/bin/startup.sh
